package com.honglu.headline.rule.config.facade.domain;

import java.io.Serializable;

public class BuVideoPkActivity  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.video_pk_id
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String videoPkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.video_one_id
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String videoOneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.video_one_url
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String videoOneUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.video_two_id
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String videoTwoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.video_two_url
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String videoTwoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.begin_time
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.end_time
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.state
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.create_time
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.create_man
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.modify_time
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.modify_man
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_video_pk_activity.remark
     *
     * @mbggenerated Mon Dec 11 17:58:58 CST 2017
     */
    private String remark;

    public String getVideoPkId() {
        return videoPkId;
    }

    public void setVideoPkId(String videoPkId) {
        this.videoPkId = videoPkId;
    }

    public String getVideoOneId() {
        return videoOneId;
    }

    public void setVideoOneId(String videoOneId) {
        this.videoOneId = videoOneId;
    }

    public String getVideoOneUrl() {
        return videoOneUrl;
    }

    public void setVideoOneUrl(String videoOneUrl) {
        this.videoOneUrl = videoOneUrl;
    }

    public String getVideoTwoId() {
        return videoTwoId;
    }

    public void setVideoTwoId(String videoTwoId) {
        this.videoTwoId = videoTwoId;
    }

    public String getVideoTwoUrl() {
        return videoTwoUrl;
    }

    public void setVideoTwoUrl(String videoTwoUrl) {
        this.videoTwoUrl = videoTwoUrl;
    }

    public String getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getCreateMan() {
        return createMan;
    }

    public void setCreateMan(String createMan) {
        this.createMan = createMan;
    }

    public String getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getModifyMan() {
        return modifyMan;
    }

    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}