package com.honglu.headline.rule.config.facade.domain;


import java.io.Serializable;

public class RedLevel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.id
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.level_name
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String levelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.level_multiple
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String levelMultiple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.level_percent
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String levelPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.version
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.create_time
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.create_user
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.create_user_name
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.modify_time
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.modify_user
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_level.modify_user_name
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String modifyUserName;


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getLevelName() {
        return levelName;
    }

    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    public String getLevelMultiple() {
        return levelMultiple;
    }

    public void setLevelMultiple(String levelMultiple) {
        this.levelMultiple = levelMultiple;
    }

    public String getLevelPercent() {
        return levelPercent;
    }

    public void setLevelPercent(String levelPercent) {
        this.levelPercent = levelPercent;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getCreateUserName() {
        return createUserName;
    }

    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    public String getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getModifyUser() {
        return modifyUser;
    }

    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    public String getModifyUserName() {
        return modifyUserName;
    }

    public void setModifyUserName(String modifyUserName) {
        this.modifyUserName = modifyUserName;
    }
}