package com.honglu.headline.rule.config.facade.domain;


import java.io.Serializable;


public class RedPackage  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.id
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.red_package_code
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String redPackageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.red_package_name
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String redPackageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.red_package_desc
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String redPackageDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.red_package_num
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String redPackageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.type
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.red_activity_type
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String redActivityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.red_package_count
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String redPackageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.red_package_rule
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String redPackageRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.state
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.create_time
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.create_user
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.create_user_name
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.modify_time
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.modify_user_name
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String modifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_red_package.modify_user
     *
     * @mbggenerated Thu Dec 07 11:27:35 CST 2017
     */
    private String modifyUser;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRedPackageCode() {
        return redPackageCode;
    }

    public void setRedPackageCode(String redPackageCode) {
        this.redPackageCode = redPackageCode;
    }

    public String getRedPackageName() {
        return redPackageName;
    }

    public void setRedPackageName(String redPackageName) {
        this.redPackageName = redPackageName;
    }

    public String getRedPackageDesc() {
        return redPackageDesc;
    }

    public void setRedPackageDesc(String redPackageDesc) {
        this.redPackageDesc = redPackageDesc;
    }

    public String getRedPackageNum() {
        return redPackageNum;
    }

    public void setRedPackageNum(String redPackageNum) {
        this.redPackageNum = redPackageNum;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRedActivityType() {
        return redActivityType;
    }

    public void setRedActivityType(String redActivityType) {
        this.redActivityType = redActivityType;
    }

    public String getRedPackageCount() {
        return redPackageCount;
    }

    public void setRedPackageCount(String redPackageCount) {
        this.redPackageCount = redPackageCount;
    }

    public String getRedPackageRule() {
        return redPackageRule;
    }

    public void setRedPackageRule(String redPackageRule) {
        this.redPackageRule = redPackageRule;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getCreateUserName() {
        return createUserName;
    }

    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    public String getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getModifyUserName() {
        return modifyUserName;
    }

    public void setModifyUserName(String modifyUserName) {
        this.modifyUserName = modifyUserName;
    }

    public String getModifyUser() {
        return modifyUser;
    }

    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }
}